Repository balancednetwork/balanced-network-info, pull requests merged in 2022-03, with the labels that each got.

#98 feat: tidy up sorting
  src/components/AnimatedList/index.tsx
  src/sections/PairSection.tsx
  src/sections/TokenSection.tsx
Labels: review, UX Review Complete

#94 fix: fix loan baln rewards calculation
  src/queries/index.ts
  src/utils/formatter.ts
Labels: review

#99 Feat: add FIN token
  src/assets/tokens/FIN.svg
  src/constants/currency.ts
Labels: review, Code Review Complete
